---
driver:
  name: ec2
  aws_ssh_key_id: AWS_Nova_Key
  region: us-east-1
  subnet_id: subnet-341cfe50
  instance_type: t2.micro
  image_id: ami-d5bf2caa
  security_group_ids: ["sg-9adee2eb"]
  retryable_tries: 120

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  name: ssh
  ssh_key: /Users/wescoffay/wdi/aws/ssh/AWS_Nova_Key.pem

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
